module.exports = {
  drinks: [
    {
      idDrink: '15300',
      strDrink: '3-Mile Long Island Iced Tea',
      strDrinkAlternate: null,
      strDrinkES: null,
      strDrinkDE: null,
      strDrinkFR: null,
      'strDrinkZH-HANS': null,
      'strDrinkZH-HANT': null,
      strTags: null,
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Collins Glass',
      strInstructions:
        'Fill 14oz glass with ice and alcohol. Fill 2/3 glass with cola and remainder with sweet & sour. Top with dash of bitters and lemon wedge.',
      strInstructionsES: null,
      strInstructionsDE:
        'F\u00fcllen Sie ein 12 cl. Glas mit Eis und Alkohol. F\u00fcllen Sie 2/3 des Glases mit Cola und den Rest mit S\u00fc\u00df-Sauer. Mit einem Schuss Bitter und Zitronenkeil garnieren.',
      strInstructionsFR: null,
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb:
        'https://www.thecocktaildb.com/images/media/drink/rrtssw1472668972.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Light rum',
      strIngredient3: 'Tequila',
      strIngredient4: 'Triple sec',
      strIngredient5: 'Vodka',
      strIngredient6: 'Coca-Cola',
      strIngredient7: 'Sweet and sour',
      strIngredient8: 'Bitters',
      strIngredient9: 'Lemon',
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/2 oz ',
      strMeasure2: '1/2 oz ',
      strMeasure3: '1/2 oz ',
      strMeasure4: '1/2 oz ',
      strMeasure5: '1/2 oz ',
      strMeasure6: null,
      strMeasure7: '1-2 dash ',
      strMeasure8: '1 wedge ',
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-08-31 19:42:52',
    },
  ],
};
